# Generated by Django 4.2.2 on 2023-06-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='departamento')),
                ('latitud', models.CharField(blank=True, max_length=20, null=True)),
                ('longitud', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(default='-', max_length=25, verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nivel Educación')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nivel Educación',
                'verbose_name_plural': 'Niveles de Educación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='help_text', max_length=20, verbose_name='Estado Civil')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='municipio')),
                ('latitud', models.CharField(blank=True, max_length=20, null=True)),
                ('longitud', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(default='-', max_length=30, verbose_name='categoría')),
                ('dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='provincia')),
                ('ecodigo', models.IntegerField(blank=True, null=True)),
                ('cdesred', models.CharField(blank=True, max_length=5, null=True)),
                ('cvalor', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['documento'],
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Vivienda')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Rubro Económico')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubro Económico',
                'verbose_name_plural': 'Rubros Económico',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombres')),
                ('numero', models.CharField(default=0, help_text='Sin puntos', max_length=12, unique=True, verbose_name='Número')),
                ('cuil', models.CharField(help_text='Sin guiones', max_length=11, unique=True, verbose_name='CUIL')),
                ('vive', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(help_text='Correo Electrónico', max_length=254, unique=True)),
                ('domicilio', models.CharField(max_length=80)),
                ('cp', models.CharField(help_text='Ejemplo 4700', max_length=10, verbose_name='Código Postal')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dpto', models.ForeignKey(default='Capital', on_delete=django.db.models.deletion.PROTECT, to='app_general.departamento', verbose_name='Departamento')),
                ('educacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.educacion')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.estadocivil', verbose_name='Estado Civil')),
                ('municipio', models.ForeignKey(default='Capital', on_delete=django.db.models.deletion.PROTECT, to='app_general.municipio')),
                ('provincia', models.ForeignKey(default='Catamarca', on_delete=django.db.models.deletion.PROTECT, to='app_general.provincia')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.rubro', verbose_name='Rubro Económico')),
                ('sexo', models.ForeignKey(default='Masculino', on_delete=django.db.models.deletion.PROTECT, to='app_general.sexo')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.tipodocumento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.vivienda')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo Hijo/a', max_length=20, unique=True, verbose_name='Parentesco')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_general.provincia'),
        ),
    ]
