# Generated by Django 4.2.2 on 2023-06-30 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerarquia', models.PositiveSmallIntegerField(help_text='Ejemplo 1 Mayor jerarquia ', verbose_name='gerarquia')),
                ('cargo', models.CharField(max_length=100)),
                ('membresia', models.CharField(blank=True, help_text='Ejemplo Dra. C.P.N.', max_length=10, null=True, verbose_name='Titulo de membresia')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombres')),
                ('imagen', models.ImageField(default='img/autoridades/no-img.jpg', upload_to='img/autoridades/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['jerarquia'],
            },
        ),
    ]
