# Generated by Django 4.2.2 on 2023-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_autoridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='imagen',
            field=models.ImageField(default='img/autoridades/no-img.jpg', upload_to='autoridades'),
        ),
    ]
