# Generated by Django 4.2.2 on 2023-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_alter_autoridad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='imagen',
            field=models.ImageField(default='autoridades/avatar_null.jpg', upload_to='autoridades'),
        ),
    ]
