# Generated by Django 4.2.2 on 2023-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='plazo',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
