# Generated by Django 4.2.2 on 2023-06-28 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_creditos', '0003_alter_linea_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='plazo',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
