# Generated by Django 4.2.2 on 2023-06-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
        ('app_emprendimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.persona'),
        ),
    ]
